### ISSUE TITLE
Remove node_modules

### ISSUE THREAD

**Issue by MaanasVohra** [SSPrafulTondomker/MCQ#8]
The node_modules folder ends up taking a lot of space while downloading on slow networks. Instead of this, the folder could be deleted and if all dependencies are there in the package.json file then they could be simply installed using :
`npm install`

**Comment by SSPrafulTondomker** [comment]
We appreciate your participation in our project and thank you for your valuable suggestion, the above mention folder has been deleted. If you find any more bug, or any useless folder gaining the large space, kindly let us now.
